// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentProject.Infra.CrossCutting.Bus.Sagas.Context;

#nullable disable

namespace StudentProject.Infra.CrossCutting.Bus.Migrations
{
    [DbContext(typeof(MassTransitDbContext))]
    partial class MassTransitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("mst")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentProject.Infra.CrossCutting.Bus.Sagas.Datas.StudentCreatedThirdPartyRegistrationSagaData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("correlation_id");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("current_state");

                    b.Property<DateTime?>("RequestCreateStudentThirdPartyUIdSendedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_create_student_third_party_uid_sended_at");

                    b.Property<DateTime?>("ResponseCreateStudentThirdPartyUIdReceivedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("response_create_student_third_party_uid_received_at");

                    b.Property<DateTime?>("ResponseCreateStudentThirdPartyUIdWaitedLastAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("response_create_student_third_party_uid_waited_last_at");

                    b.Property<DateTime?>("StudentThirdPartyUIdUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("student_third_party_uid_updated_at");

                    b.Property<Guid>("StudentUId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_uid");

                    b.HasKey("CorrelationId")
                        .HasName("PKstudentcreatedthirdpartyregistrationsagadata");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("CorrelationId"));

                    b.ToTable("tb_student_created_third_party_registration_saga_data", "mst");
                });
#pragma warning restore 612, 618
        }
    }
}
